gcc5 + gcc6 fix compiles gcc5: gpu: msm: fix 5.0 compile
* These need to be static to avoid these errors:

drivers/built-in.o: In function `.LANCHOR1':
msm_iommu_sec.c:(.data+0x9298): undefined reference to `kgsl_iommu_sync_lock'
msm_iommu_sec.c:(.data+0x929c): undefined reference to `kgsl_iommu_sync_unlock'
Makefile:877: recipe for target '.tmp_vmlinux1' failed
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

gcc5: fix warnings spam with gcc5

This fixes 102 warnings

Signed-off-by: Paul Beeler <pbeeler80@gmail.com>

gcc5: sound/soc/codecs/wcd9xxx-mbhc.c fix warning: initialization discards 'const' qualifier from pointer target type

gcc5: drivers/staging/prima/CORE/MAC/src/pe/sch/schBeaconGen.c: fix warning: passing argument 2 of 'vos_mem_compare' discards 'const' qualifier from pointer target type

gcc5: drivers/staging/prima/CORE/HDD/src/wlan_hdd_wmm.c: fix warning: logical not is only applied to the left hand side of comparison

gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: fix warning: logical not is only applied to the left hand side of comparison

gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: fix warning: comparison of constant '15' with boolean expression is always false

gcc5: suppress more warnings

gcc5: makefile: remove wrapper

gcc5: try to fix errors

gcc5: try to fix again

gcc6: get compiler-gcc6.h

Credits to @rachanta.

gcc6:Supress warning and remove errors in return_address.c

fix swp{b} use is deprecated for ARMv6 and ARMv7

Signed-off-by: shivamk11 <shivamk11@gmail.com>

gcc6:Fix errors in ftrace.h

msm: qcrypto: remove duplicate define for list_next_entry

net: ipv6: Amend ipv6_recv_error usage

Usage of ipv6_recv_error, included in commit f704820, needs to be
updated to account for the changes in ad25b5d.

Fixes:
  net/ipv6/ping.c: In function 'pingv6_init':
  net/ipv6/ping.c:84:29: warning: assignment from incompatible pointer type [enabled by default]

Change-Id: Ia77db6e465072fb794999a20f75f59e848a88b79
Signed-off-by: Luis Cruz <ljc2491@gmail.com>

Remove '+' symbol from kernel version string

Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>
Signed-off-by: Francisco Franco <franciscofranco.1990@gmail.com>

drivers/usb/gadget/Kconfig:881:warning: defaults for choice values

not supported

Change-Id: I597f88f7001dfbdb8a61bdee263e626b327a5d36

slub: Initialize x and fix build

Change-Id: Id4d880255838e9d7cd09aa69e609978d44ba3513

overlayfs: inode: Fix build

From rasa/vmware-tools-patches@3a392a590b873bfeb515a36240c2d1510e87675c

Change-Id: I5f41a378593c35b282790aa31b6c19cd66c8b893